version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prd_tastedash_svc_vue-admin
    ports:
      - 3010:80  # Maps host port 3010 to container port 80

  nginx:
    image: nginx:alpine
    container_name: prd_tastedash_svc_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8088:80  # Maps host port 8088 to container port 80
    depends_on:
      - app
